// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransverseApiSessionCDR.Infrastructure;

#nullable disable

namespace MellmothJdr.DAL.Migrations
{
    [DbContext(typeof(MigrationContext))]
    [Migration("20250225104259_Classes2")]
    partial class Classes2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Classe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateMaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("JeuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("JeuId");

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88a45295-7a95-487e-b881-fb9e0580a2a5"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Arquebusier"
                        },
                        new
                        {
                            Id = new Guid("0b7fd2d0-c2ad-4492-ab38-f741174d5a6d"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Barbare"
                        },
                        new
                        {
                            Id = new Guid("91b825c3-3e5a-4e1b-8724-daf18ea27c6a"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Barde"
                        },
                        new
                        {
                            Id = new Guid("c67e5709-a257-4dcd-9250-6c2786327091"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Chevalier"
                        },
                        new
                        {
                            Id = new Guid("a91093ab-cdec-4d36-8e30-9393a955c382"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Druide"
                        },
                        new
                        {
                            Id = new Guid("2048962d-f0d3-460b-a054-fae5ea578cc3"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Ensorceleur"
                        },
                        new
                        {
                            Id = new Guid("7b00f70a-4e76-4d4c-8df5-c7ffe0022c20"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Forgesort"
                        },
                        new
                        {
                            Id = new Guid("b27608e8-b453-4397-8d41-7c3c3d9af293"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Guerrier"
                        },
                        new
                        {
                            Id = new Guid("1a4b34b8-2752-4062-a0e5-59695a79d9c7"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Magicien"
                        },
                        new
                        {
                            Id = new Guid("e6d9a3ba-1dcc-4e33-859f-615dbbf3717f"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Moine"
                        },
                        new
                        {
                            Id = new Guid("ded836b7-688e-4757-b100-1dc146142846"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Nécromancien"
                        },
                        new
                        {
                            Id = new Guid("f5d228cd-75ee-4462-a2a7-102383250bdd"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Prêtre"
                        },
                        new
                        {
                            Id = new Guid("6e3fd8e2-1680-4a8b-b928-1e48acc20861"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Rôdeur"
                        },
                        new
                        {
                            Id = new Guid("0441eff4-f2ca-4757-b02e-3e1043cf4234"),
                            DateCrea = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            Libelle = "Voleur"
                        });
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.FichesPersos.FichePersoChroniquesOublies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCrea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateMaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid?>("JeuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<Guid?>("PartieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PoidKg")
                        .HasColumnType("int");

                    b.Property<int>("PvEnCours")
                        .HasColumnType("int");

                    b.Property<int>("PvMax")
                        .HasColumnType("int");

                    b.Property<Guid?>("RaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RaceLibelle")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TailleCm")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JeuId");

                    b.HasIndex("PartieId");

                    b.HasIndex("RaceId");

                    b.HasIndex("UserId");

                    b.ToTable("FichesPersoChroniquesOublies", (string)null);
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Jeu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateMaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Jeux", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fc4e9f5-e8a8-4269-9dbc-2e5c4af3b2b1"),
                            DateCrea = new DateTime(2025, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Le jeu de rôle Dungeons & Dragons consiste à narrer des aventures dans des mondes peuplés de guerriers et de magiciens. Tout comme les jeux où l'on s'amuse à faire semblant, D&D repose sur l'imagination.\r\n\r\nDans ce monde fantastique, les possibilités sont infinies.",
                            Nom = "Donjons & Dragons"
                        },
                        new
                        {
                            Id = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            DateCrea = new DateTime(2025, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chroniques Oubliées, conçue pour la découverte du JdR, est la version modernisée et simplifiée (mais pas simpliste) du premier des jeux de rôle. Aux mécaniques de base viennent s'ajouter des \"briques\" modulaires, optionnelles, pour enrichir l'expérience de jeu.\r\n\r\nSi vous souhaitiez découvrir (ou faire découvrir) le jeu de rôle ou si vous êtes à la recherche d'un jeu rapide à mettre en place pour renouer avec le loisir, ne cherchez pas plus loin !\r\n\r\nChroniques Oubliées se décline aujourd'hui dans sa version Fantasy (univers médiéval-fantastique), Contemporain (multiples univers possibles couvrant la période 1900-2100 : horreur lovecraftienne, pulp, zombies, vampires, super-héros, espionnage, policier, cyberpunk...) et Galactique (univers de science-fiction en trois époques : Space Opera, temps de la colonisation galactique et Hard Science).",
                            Nom = "Chroniques Oublies"
                        });
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Jointures.JoinFichePersoChroniquesOubliesClasse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClasseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateMaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("FichePersoChroniquesOubliesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("FichePersoChroniquesOubliesId");

                    b.ToTable("JoinFichePersoChroniquesOubliesClasses", (string)null);
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Partie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateMaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("JeuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("NombreParticipant")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JeuId");

                    b.HasIndex("UserId");

                    b.ToTable("Parties", (string)null);
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateMaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("JeuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RaceLibelle")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("JeuId");

                    b.ToTable("Races", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            DateCrea = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L’humain se distingue par sa capacité d’adaptation et son instinct qui le pousse à coloniser tous les territoires qui l’entourent. La Race humaine est la plus représentée et la plus répandue dans les zones dites \"civilisées\".\r\n\r\nLes humains sont de jeunes loups ignorants, ils croissent et se multiplient sans aucun respect pour l’équilibre du monde, leur égoïsme et leur égocentrisme semblent sans limite. Ils mèneront le monde entier à la catastrophe si personne ne les arrête.",
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            RaceLibelle = "Humains"
                        },
                        new
                        {
                            Id = new Guid("9c8d7e6f-5b4a-1234-cde9-0f1e2d3c4b5a"),
                            DateCrea = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Le Haut-elfe est un être féerique qui vit extrêmement longtemps. Il est méprisant envers les Nains et arrogant envers les autres races. Proche de la nature, il maîtrise aussi bien les arts de la magie que ceux de la guerre.\r\n\r\nLes Elfes se croient supérieurs à tous les autres, ce sont de puissants magiciens mais leur cœur est sans pitié. Ils obéissent à de très anciennes règles et à des serments incompréhensibles pour les Races à l’espérance de vie ordinaire.",
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            RaceLibelle = "Elfe, haut"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-47a8-90ab-cdef12345678"),
                            DateCrea = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Le Nain est petit mais robuste. Célèbre pour sa barbe, il aime les profondeurs de la terre, dont il extrait des métaux et des pierres précieuses. Isolé, il est généralement ouvert et chaleureux, mais la société naine peut paraître sévère car le travail et l’entraînement militaire y sont des obligations.\r\n\r\nLes Nains aiment amasser de l’or et boire de la bière en compagnie d’autres Nains. Ils sont un peu rustres et très susceptibles, un Nain peut se mettre en colère et devenir violent pour des raisons qui semblent étranges voire futiles à un autre peuple…",
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            RaceLibelle = "Nains"
                        },
                        new
                        {
                            Id = new Guid("01234567-89ab-cdef-0123-456789abcdef"),
                            DateCrea = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Le Demi-elfe a hérité des qualités de ses deux parents (humain et Elfe). Il est généralement traité avec condescendance parmi les Elfes et est considéré comme un Elfe parmi les humains.\r\n\r\nLes Demi-elfes sont des artistes hors-pair dotés d'une grande sensibilité. Toutefois, attention car ils sont beaux parleurs et manipulateurs : cachez vos filles et vos femmes, ils ont brisé plus d'un cœur et corrompu bien des dames de réputation vertueuse.",
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            RaceLibelle = "Demi-Elfes"
                        },
                        new
                        {
                            Id = new Guid("fedcba98-7654-3210-fedc-ba9876543210"),
                            DateCrea = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Le Halfelin est la plus petite des races jouables. Toujours bon vivant, souvent vif, curieux, et parfois farceur, c’est un incompris que les autres Races considèrent souvent comme turbulent, pénible, voire parfois comme un voleur.\r\n\r\nLes Halfelins sont inoffensifs et ne pensent qu’à bien manger. Toutefois, ne perdez jamais de vue leurs mains car se sont aussi des voleurs sans scrupules.",
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            RaceLibelle = "Halfelins"
                        },
                        new
                        {
                            Id = new Guid("13579bdf-2468-ace0-bdf1-3579bdf24680"),
                            DateCrea = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Demi-orque\r\nLe Demi-orque est de grande taille. Issu de l’union souvent forcée d’une humaine et d’un Orque, il possède une force physique hors du commun. Il est généralement méprisé par les autres races, en particulier par les Nains et les Elfes.\r\n\r\nLes Demi-orques sont violents, sales et stupides, ils en veulent au monde entier de leur ignoble naissance et mieux vaut les éviter",
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            RaceLibelle = "Demi-orques"
                        },
                        new
                        {
                            Id = new Guid("11223344-5566-7788-99aa-bbccddeeff00"),
                            DateCrea = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L’Elfe sylvain est issu d’une culture différente de celle des Hauts-elfes. Légèrement plus petits, ils vivent au plus profond des forêts, s’abritant dans les arbres et vivant simplement de la chasse et de la cueillette. Moins arrogants que leurs cousins Hauts-elfes, ils sont cependant beaucoup plus méfiants. Ils maitrisent particulièrement l’art du camouflage et l’utilisation de l’arc.\r\n\r\nLes Elfes sylvains sont de redoutables archers, ils détestent les cités et les gens qui y vivent, ils peuvent tuer d’une flèche dans le dos un paysan juste parce qu'il a coupé le mauvais arbre.",
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            RaceLibelle = "Elfe, sylvain"
                        },
                        new
                        {
                            Id = new Guid("abcdef12-3456-7890-abcd-ef1234567890"),
                            DateCrea = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateMaj = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Le Gnome est une créature de petite taille pourvue d’un gros nez, d’une bonne nature et d’une curiosité insatiable pour la magie et les sciences. C’est un compagnon souvent agréable bien qu’un peu original. Les Nains et les Halfelins l’apprécient, tandis que les \"grandes\" races se montrent plutôt indifférentes à leur égard.\r\n\r\nLes Gnomes sont sympathiques mais à moitié fous, méfiez-vous comme de la peste de leurs inventions ou de leurs projets farfelus.",
                            JeuId = new Guid("1c474c24-f5c9-470e-9b91-046b639275c3"),
                            RaceLibelle = "Gnome"
                        });
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateMaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("ExterneId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Classe", b =>
                {
                    b.HasOne("MellmothJdr.DAL.Entities.Jeu", "Jeu")
                        .WithMany("Classes")
                        .HasForeignKey("JeuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jeu");
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.FichesPersos.FichePersoChroniquesOublies", b =>
                {
                    b.HasOne("MellmothJdr.DAL.Entities.Jeu", "Jeu")
                        .WithMany("FichesPersoChroniquesOublies")
                        .HasForeignKey("JeuId");

                    b.HasOne("MellmothJdr.DAL.Entities.Partie", "Partie")
                        .WithMany("FichePersoChroniqueOublies")
                        .HasForeignKey("PartieId");

                    b.HasOne("MellmothJdr.DAL.Entities.Race", "Race")
                        .WithMany("FichesPersoChroniquesOublies")
                        .HasForeignKey("RaceId");

                    b.HasOne("MellmothJdr.DAL.Entities.User", "User")
                        .WithMany("FichePersoChroniqueOublies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jeu");

                    b.Navigation("Partie");

                    b.Navigation("Race");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Jointures.JoinFichePersoChroniquesOubliesClasse", b =>
                {
                    b.HasOne("MellmothJdr.DAL.Entities.Classe", "Classe")
                        .WithMany("JoinFichePersoChroniquesOubliesClasses")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MellmothJdr.DAL.Entities.FichesPersos.FichePersoChroniquesOublies", "FichePersoChroniquesOublies")
                        .WithMany("JoinFichePersoChroniquesOubliesClasses")
                        .HasForeignKey("FichePersoChroniquesOubliesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("FichePersoChroniquesOublies");
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Partie", b =>
                {
                    b.HasOne("MellmothJdr.DAL.Entities.Jeu", "Jeu")
                        .WithMany("Parties")
                        .HasForeignKey("JeuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MellmothJdr.DAL.Entities.User", "User")
                        .WithMany("Parties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jeu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Race", b =>
                {
                    b.HasOne("MellmothJdr.DAL.Entities.Jeu", "Jeu")
                        .WithMany("Races")
                        .HasForeignKey("JeuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jeu");
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Classe", b =>
                {
                    b.Navigation("JoinFichePersoChroniquesOubliesClasses");
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.FichesPersos.FichePersoChroniquesOublies", b =>
                {
                    b.Navigation("JoinFichePersoChroniquesOubliesClasses");
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Jeu", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("FichesPersoChroniquesOublies");

                    b.Navigation("Parties");

                    b.Navigation("Races");
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Partie", b =>
                {
                    b.Navigation("FichePersoChroniqueOublies");
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.Race", b =>
                {
                    b.Navigation("FichesPersoChroniquesOublies");
                });

            modelBuilder.Entity("MellmothJdr.DAL.Entities.User", b =>
                {
                    b.Navigation("FichePersoChroniqueOublies");

                    b.Navigation("Parties");
                });
#pragma warning restore 612, 618
        }
    }
}
